CReate database SpaceJam

USE SpaceJam

CREATE TABLE ToonSquad(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
UserId NVARCHAR(450) FOREIGN KEY REFERENCES AspNetUsers(Id),
Player1 NVARCHAR(20),
Player2 NVARCHAR(20),
Player3 NVARCHAR(20),
Player4 NVARCHAR(20),
Player5 NVARCHAR(20),)

CREATE TABLE Monstars(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
UserId NVARCHAR(450) FOREIGN KEY REFERENCES AspNetUsers(Id),
Pound NVARCHAR(20),
Bupkus NVARCHAR(20),
Nawt NVARCHAR(20),
Bang NVARCHAR(20),
Blanko NVARCHAR(20),)

CREATE TABLE PlayerStats(
PlayerId NVARCHAR(20) PRIMARY KEY,
PlayerName NVARCHAR(50),
Points float,
Assists FLOAT,
Rebounds FLOAT,
Blocks FLOAT,
Steals FLOAT)

